#!/bin/bash
#SCRIPT INSTALLATION NAMEDMANAGER (FEDORA20 /CENTOS7)
#OUSMANE SANOGO

#mise a jour du server et on install wget nano et apache

yum -y update

yum -y install \
	wget \
	nano \
	httpd 

#ajout du repo de mysql pour centos7

rpm --import http://repo.mysql.com/RPM-GPG-KEY-mysql
wget -O /etc/yum.repos.d/mysql-community.repo http://kimsufi1.sanogo.net/repos/mysql-community.repo
wget -O /etc/yum.repos.d/mysql-community-source.repo http://kimsufi1.sanogo.net/repos/mysql-community-source.repo

#on install mysql
yum -y install \
	mysql-server 

#on install les paquets necessaire pour namedmanager

yum install -y \
	php \
	php-gd \
	php-pear \
	php-intl \
	php-soap \
	php.x86_64 \
	perl-DBD-MySQL \
	php-intl \
	php-ldap \
	php-mysql \
	php-soap \
	php-xml \
	mod_ssl \
	php-process \
	bind.x86_64

#on recupere et install les rpm de la version 7 de centos ou fedora (21,22)

rpm --import http://repos.jethrocarr.com/jethrocarr_signing_key.gpg
wget -O /etc/yum.repos.d/jethrocarr-c7-public.repo http://repos.jethrocarr.com/config/centos/7/jethrocarr-c7-public.repo

yum -y install  \
	namedmanager-www \
	namedmanager-bind

#on modifie le fichier named.conf pour que le check soit fait par toute les ip du server

sed -i 's/\tlisten-on port 53.*;$/\tlisten-on port 53 { any; };/g' /etc/named.conf
sed -i 's/\tlisten-on-v6 port*;$/\tlisten-on-v6 port 53 { any; };/g' /etc/named.conf
sed -i 's/\tallow-query*;/\tallow-query { any; };/g' /etc/named.conf
sed -i ' $ a include /etc/named.namedmanager.conf;' /etc/named.conf


#on start mysql et apache

systemctl start mysqld httpd
systemctl enable mysqld httpd

#on ouvre les ports 53,80 et 443

firewall-cmd --add-service=dns --add-service=http --add-service=https --permanent
firewall-cmd --reload

#on modifie le passwd de la bd

mysql -e "UPDATE mysql.user SET Password = PASSWORD('changeme') WHERE User = 'root'"
mysql -e "DROP USER ''@'localhost'"
mysql -e "DROP USER ''@'$(hostname)'"
mysql -e "FLUSH PRIVILEGES"

#on modifie les droits d'acces au webroot

sed -i 's/\tOrder.*/\t#/g' /etc/httpd/conf.d/namedmanager.conf
sed -i 's/\tAllow from.*/\t#/g' /etc/httpd/conf.d/namedmanager.conf
sed -i '/<\/Location>/ i \\tRequire all granted' /etc/httpd/conf.d/namedmanager.conf

#on modifie les logs de namedmanager

myip=`ifconfig eth0 | awk ' /inet/ { print $2 } ' | grep -v '^[a-z].*'`
touch /var/log/namedmanager_messages

sed -i 's/\/var\/log\/messages/\/var\/log\/namedmanager_messages/g' /etc/namedmanager/config-bind.php
sed -i 's/http:\/\/example.com\/namedexample/http:\/\/$myip\/namedmanager/g' /etc/namedmanager/config-bind.php
sed -i "s/dnsmaster.example.com/$myip/g" /etc/namedmanager/config-bind.php
sed -i "s/localhost/$myip/g" /etc/namedmanager/config.php
sed -i "s/ultrahighsecretkey/`date +%s | sha256sum | base64 | head -c 32 ; echo`/g" /etc/namedmanager/config-bind.php

#on ajoute le pass de la BDD
sed -i 's/^my $db_pass.*/my $db_pass = "changeme";/g' /usr/share/namedmanager/resources/autoinstall.pl

#on install la bd

/usr/share/namedmanager/resources/autoinstall.pl

systemctl restart httpd
#Fin installation
#on peut enfin se connecter sur le lien "http://IP/namedmanager"
echo "on peut enfin se connecter sur le lien http://$myip/namedmanager"
